name = "public-documents"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[build]
command = ""

[build.upload]
format = "service-worker"
main = "./index.ts"

[[build.upload.rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true

[[build.upload.rules]]
type = "Text"
globs = ["**/*.txt", "**/*.html", "**/*.md"]
fallthrough = true

[[build.upload.rules]]
type = "Data"
globs = ["**/*.pdf", "**/*.jpg", "**/*.jpeg", "**/*.png", "**/*.gif", "**/*.webp", "**/*.svg"]
fallthrough = true
